version: 0.0
os: linux
files:
  - source: /
    destination: home/ubuntu/java

hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      runas: root

  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 180
      runas: root
  
